# Generated by Django 6.0.6 on 2026-07-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_emailconfirmationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
