# Generated by Django 6.0.6 on 2026-07-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Comedy', 'Comedy')], default='General', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional: If left blank, a thumbnail will be automatically generated from the video.', null=True, upload_to='thumbnails/')),
                ('raw_video_file', models.FileField(upload_to='videos/raw/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
